CREATE TABLE `authNameLog` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uid` BIGINT UNSIGNED NOT NULL,`val` VARBINARY(255) NOT NULL,`ts` BIGINT UNSIGNED NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),UNIQUE KEY `unique` (`uid`,`val`)
);