CREATE TABLE `authPasswd` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`hostId` BIGINT UNSIGNED NOT NULL,`uid` BIGINT UNSIGNED NOT NULL,`hash` BINARY(16) NOT NULL,`ts` BIGINT UNSIGNED NOT NULL DEFAULT current_timestamp(),PRIMARY KEY (`id`),UNIQUE KEY `unique` (`hostId`,`uid`)
);