CREATE TABLE `payCashLog` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`uid` BIGINT UNSIGNED NOT NULL,`n` BIGINT NOT NULL,`cid` BIGINT UNSIGNED NOT NULL,`rid` BIGINT UNSIGNED NOT NULL,`ts` BIGINT UNSIGNED NOT NULL DEFAULT current_timestamp(),`cash` BIGINT UNSIGNED NOT NULL,PRIMARY KEY (`id`)
);