CREATE FUNCTION `authArchId`(v VARBINARY(255)) RETURNS int(20) UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authArch WHERE val=v;
  IF r IS NULL THEN
    INSERT INTO authArch (val) VALUES (v);
    RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;