CREATE FUNCTION `authGpuId`(v VARBINARY(255)) RETURNS INT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authGpu WHERE val=v;
  IF r IS NULL THEN
    INSERT INTO authGpu (val) VALUES (v);
    RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;