CREATE FUNCTION `authOsId`(v VARBINARY(255)) RETURNS INT UNSIGNED
BEGIN
  DECLARE r BIGINT UNSIGNED;
  SELECT id INTO r FROM authOs WHERE val=v;
  IF r IS NULL THEN INSERT INTO authOs (val) VALUES (v); RETURN LAST_INSERT_ID();
END IF;
RETURN r;
END ;;